name: Format with Ruff

on:
  push:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - uv.lock
  pull_request:
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - uv.lock

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          args: format --check --diff
